package com.anabelen.api.model; 

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable; 

@DynamoDBTable(tableName = "anabelen-products") 
public class Product { 
    

    private String id;
    private String name; 
    private String description; 
    private Double price; 
    private Integer stock; 
    private String mimoCategory; 

    @DynamoDBHashKey(attributeName = "id") 
    @DynamoDBAutoGeneratedKey 
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "name") 
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "price") 
    public Double getPrice() {
        return price;
    }
    public void setPrice(Double price) {
        this.price = price;
    }

    @DynamoDBAttribute(attributeName = "stock") 
    public Integer getStock() {
        return stock;
    }
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    @DynamoDBAttribute(attributeName = "mimoCategory") 
    public String getMimoCategory() {
        return mimoCategory;
    }
    public void setMimoCategory(String mimoCategory) {
        this.mimoCategory = mimoCategory;
    }

    
    public Product() {}

    
    public Product(String name, String description, Double price, Integer stock, String mimoCategory) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stock = stock;
        this.mimoCategory = mimoCategory;
    }
}